### ISSUE TITLE
Suspicious combine jobs at surfsara

### ISSUE THREAD

**Issue by FaroutYLq** [XENONnT/outsource#56]
In principle we don't want any jobs to run outside USA, otherwise it might leads to transferring headache. 

This is an example bad batch which basically did nothing. You can see massive failure in combine jobs: `/scratch/yuanlq/workflows/runs/straxen_v2.1.1/xenonnt_offline/sr1_hotspot_batch_1_1`.  For example this piece from `/scratch/yuanlq/workflows/runs/straxen_v2.1.1/xenonnt_offline/sr1_hotspot_batch_1_1/00/09/combine_ID0000463.out.004`
```
---------------pegasus-multipart
- transfer_attempts:
  - src_url: "file:///srv/pegasus.N7Q2EGPSS/046503-peaklets-combined.tar.gz"
    src_label: "condorpool"
    dst_url: "gsiftp://xenon-gridftp.grid.uchicago.edu:2811/xenon/workflow_scratch/yuanlq/sr1_hotspot_batch_1_1/00/08/046503-peaklets-combined.tar.gz"
    dst_label: "staging"
    success: False
    start: 1689999168
    duration: 0.0
    lfn: "046503-peaklets-combined.tar.gz"
  - src_url: "file:///srv/pegasus.N7Q2EGPSS/046503-peaklets-combined.tar.gz"
    src_label: "condorpool"
    dst_url: "gsiftp://xenon-gridftp.grid.uchicago.edu:2811/xenon/workflow_scratch/yuanlq/sr1_hotspot_batch_1_1/00/08/046503-peaklets-combined.tar.gz"
    dst_label: "staging"
    success: False
    start: 1689999307
    duration: 0.0
    lfn: "046503-peaklets-combined.tar.gz"
  - src_url: "file:///srv/pegasus.N7Q2EGPSS/046503-peaklets-combined.tar.gz"
    src_label: "condorpool"
    dst_url: "gsiftp://xenon-gridftp.grid.uchicago.edu:2811/xenon/workflow_scratch/yuanlq/sr1_hotspot_batch_1_1/00/08/046503-peaklets-combined.tar.gz"
    dst_label: "staging"
    success: False
    start: 1689999609
    duration: 0.0
    lfn: "046503-peaklets-combined.tar.gz"
``` 

We need to go through codes again to see where it could lead to such issue.

**Comment by FaroutYLq** [comment]
These guys are suspicious.
- https://github.com/XENONnT/outsource/blob/c2db0873adb97f24fc04386eb53f5fea74f010d9/outsource/Outsource.py#L576-L602
- https://github.com/XENONnT/outsource/blob/c2db0873adb97f24fc04386eb53f5fea74f010d9/outsource/Outsource.py#L605-L619

**Comment by FaroutYLq** [comment]
We can see something like this in the generated workflow
```
      request_cpus: '1'
      request_disk: ifthenelse(isundefined(DAGNodeRetry) || DAGNodeRetry == 0, 40000000,
        (DAGNodeRetry + 1)*40000000)
      request_memory: ifthenelse(isundefined(DAGNodeRetry) || DAGNodeRetry == 0, 20000,
        (DAGNodeRetry + 1)*20000)
      +XENON_DESIRED_Sites: '"SURFsara"'
      requirements: HAS_SINGULARITY && HAS_CVMFS_xenon_opensciencegrid_org && (GLIDEIN_Site
        == "SURFsara" || GLIDEIN_Country == "US") && (GLIDEIN_Site =!= "SU-ITS" &&
        GLIDEIN_Site =!= "NotreDame" && GLIDEIN_Site =!= "UConn-HPC" && GLIDEIN_Site
        =!= "Purdue Geddes" && GLIDEIN_Site =!= "Chameleon" && GLIDEIN_Site =!= "WSU-GRID"
        && GLIDEIN_Site =!= "SIUE-CC-production" && GLIDEIN_Site =!= "Lancium")
```
Apparently, we don't want SURFsara at all.

**Comment by FaroutYLq** [comment]
Added `SURFsara` into `exclude_sites` of  `.xenon_config`. Let's see if it helps.

**Comment by FaroutYLq** [comment]
No. They still fail. This one is interesting
```
001 (27204615.000.000) 2023-07-22 09:07:11 Job executing on host: <128.105.69.246:33281?CCBID=128.104.103.162:9618%3faddrs%3d128.104.103.162-9618%26alias%3dospool-ccb.osg.chtc.io%26noUDP%26sock%3dcollector8#1127162%20192.170.231.9:9618%3faddrs%3d192.170.231.9-9618+[fd85-ee78-d8a6-8607--1-d56f]-9618%26alias%3dospool-ccb.osgprod.tempest.chtc.io%26noUDP%26sock%3dcollector2#6134982&PrivNet=mcdanielgpu4001.chtc.wisc.edu&addrs=128.105.69.246-33281+[2607-f388-2200-100-3eec-efff-fe1e-deb4]-33281&alias=mcdanielgpu4001.chtc.wisc.edu&noUDP>
        SlotName: slot1_1@mcdanielgpu4001.chtc.wisc.edu
        CondorScratchDir = "/var/lib/condor/execute/slot9/dir_1955620/glide_54exym/execute/dir_2426249"
        Cpus = 1
        Disk = 176984347
        GLIDEIN_ResourceName = "GLOW"
        Memory = 8576
...
006 (27204615.000.000) 2023-07-22 09:07:21 Image size of job updated: 2865524
        70  -  MemoryUsage of job (MB)
        70788  -  ResidentSetSize of job (KB)
...
006 (27204615.000.000) 2023-07-22 09:12:21 Image size of job updated: 5858744
        70  -  MemoryUsage of job (MB)
        70788  -  ResidentSetSize of job (KB)
...
006 (27204615.000.000) 2023-07-22 09:22:23 Image size of job updated: 13842508
        2529  -  MemoryUsage of job (MB)
        2589388  -  ResidentSetSize of job (KB)
...
006 (27204615.000.000) 2023-07-22 09:27:23 Image size of job updated: 13842508
        2754  -  MemoryUsage of job (MB)
        2819840  -  ResidentSetSize of job (KB)
...
012 (27204615.000.000) 2023-07-22 09:29:23 Job was held.
        The job disk usage exceeded 200 GBs
        Code 26 Subcode 0
...
009 (27204615.000.000) 2023-07-22 09:30:14 Job was aborted.
        The job attribute PeriodicRemove expression '((JobStatus == 2) && ((CurrentTime - EnteredCurrentStatus) > 18000)) || ((JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 30))' evaluated to TRUE

        Job terminated by SHADOW <192.170.231.225:9618?addrs=192.170.231.225-9618+[2605-9a00-10-200b-21b-21ff-fe90-cc00]-9618&alias=login.xenon.ci-connect.net&noUDP&sock=shadow_16095_2228_520412> on <192.170.231.225:16733> with reverse connect address <192.170.231.225:9618?addrs=192.170.231.225-9618+[2605-9a00-10-200b-21b-21ff-fe90-cc00]-9618&alias=login.xenon.ci-connect.net&noUDP&sock=shadow_3154667_0935_4> at 2023-07-22T14:27:23Z (using method 1: DEACTIVATE_CLAIM).
...
```
From `/scratch/yuanlq/workflows/runs/straxen_v2.1.1/xenonnt_offline/sr1_hotspot_batch_0_2`

**Comment by FaroutYLq** [comment]
What happened when staging?? From `/scratch/yuanlq/workflows/runs/straxen_v2.1.1/xenonnt_offline/sr1_hotspot_batch_0_2/00/03/combine_ID0000158.out.003`.
```
---------------pegasus-multipart
- transfer_attempts:
  - src_url: "file:///srv/pegasus.UUEsb30Cn/047297-peaklets-combined.tar.gz"
    src_label: "condorpool"
    dst_url: "gsiftp://xenon-gridftp.grid.uchicago.edu:2811/xenon/workflow_scratch/yuanlq/sr1_hotspot_batch_0_2/00/03/047297-peaklets-combined.tar.gz"
    dst_label: "staging"
    success: False
    start: 1690018465
    duration: 0.0
    lfn: "047297-peaklets-combined.tar.gz"
  - src_url: "file:///srv/pegasus.UUEsb30Cn/047297-peaklets-combined.tar.gz"
    src_label: "condorpool"
    dst_url: "gsiftp://xenon-gridftp.grid.uchicago.edu:2811/xenon/workflow_scratch/yuanlq/sr1_hotspot_batch_0_2/00/03/047297-peaklets-combined.tar.gz"
    dst_label: "staging"
    success: False
    start: 1690018597
    duration: 0.0
    lfn: "047297-peaklets-combined.tar.gz"
  - src_url: "file:///srv/pegasus.UUEsb30Cn/047297-peaklets-combined.tar.gz"
    src_label: "condorpool"
    dst_url: "gsiftp://xenon-gridftp.grid.uchicago.edu:2811/xenon/workflow_scratch/yuanlq/sr1_hotspot_batch_0_2/00/03/047297-peaklets-combined.tar.gz"
    dst_label: "staging"
    success: False
    start: 1690018899
    duration: 0.0
    lfn: "047297-peaklets-combined.tar.gz"
```
